
---
language: node_js
node_js:
  - "8"

sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

cache:
  yarn: true

env:
  - EMBER_TRY_SCENARIO=ember-2.18.X
  - EMBER_TRY_SCENARIO=ember-3.2.X
  - EMBER_TRY_SCENARIO=ember-3.4.X

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - yarn lint:js
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup